### ISSUE TITLE
Negative star count

### ISSUE THREAD

**Issue by fpg1503** [timqian/star-history#41]
When I insert `fpg1503/MakeXcodeGr8Again` it shows a star count of `-30` for 06/23/2016. I don't think that makes much sense.

**Comment by nosarthur** [comment]
https://star-history.t9t.io/#nosarthur/gita

I put in one of my project and it also has -30 stars in the beginning

**Comment by chinesedfan** [comment]
It should be caused by someone revoked the star after starred. I noticed `starred_url`, i.e. "https://api.github.com/users/nschlemm/starred{/owner}{/repo}" , but seems it doesn't work. And I didn't find a good v3 API to solve this problem.

[StargazerConnection](https://developer.github.com/v4/object/stargazerconnection/) in v4, should be more powerful. Combining with other APIs, we can even solve #31.

**Comment by timqian** [comment]
@chinesedfan Thanks for finding the root cause, I will check it out when I got time.

To my experience, people don't unstar projects very often, so this seems not a big issue for me. We can find a workaround first and then consider if it worth the effort to migrate to GitHub API v4

**Comment by chinesedfan** [comment]
@timqian After a night's thinking, I realized the real reason was something wrong in the codes.

```
// used to calculate total stars for this page
const pageIndexes = pageNum <= sampleNum ?
  range(pageNum).slice(1, pageNum) :
  range(sampleNum).map(n => Math.round(n / sampleNum * pageNum) - 1); // for bootstrap bug

// ...
starHistory = pageIndexes.map((p, i) => {
  return {
    date: resArray[i + 1].data[0].starred_at.slice(0, 10),
    starNum: 30 * (p - 1),
  };
});
```

`Math.round` is not a stable method, which means it may select a smaller or larger value. Sometimes `pageIndexes` will include 0 as the first element. That's why -30 is generated.

And I also find another place that using `Math.round`. A better way should only consider the day part of `new Date()` and calculate `daysSinceRepoCreatedAt` by `Math.ceil`.

```
const daysSinceRepoCreatedAt = Math.round((new Date()) - firstStarredAt) / (1000*60*60*24);
```
