### ISSUE TITLE
graph a little glitchy looking?

### ISSUE THREAD

**Issue by asottile** [timqian/star-history#59]
not sure if artistically intentional or if it's a bug

![](https://i.fluffy.cc/FtJqQ19Dj29mN3xKtnGs1BHx3kNzPDV1.png)

https://star-history.t9t.io/#ekalinin/nodeenv&pre-commit/pre-commit

```
# firefox on ubuntu 18.04
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0 
```

**Comment by timqian** [comment]
Hi @asottile This is intentional, I am using my new chart lib [chart.xkcd](https://github.com/timqian/chart.xkcd) to do the plots.

The idea is preventing people from taking star-history too seriously. It reflects trends of repos in some way but not precise. (Actually this motivates me create [chart.xkcd](https://github.com/timqian/chart.xkcd))

But if people don't like it, I can switch back to normal chart lib. I will keep this issue open for a while to see if we can collect any feedback

**Comment by asottile** [comment]
ah ok, so "artistically intentional" -- figured as much :)

**Comment by huangzhhui** [comment]
Please switch back to normal chart, it's almost unusable now.

**Comment by timqian** [comment]
@huangzhhui @asottile I deployed another version of star history using the previous chart lib 
 https://old-star-history.t9t.io/
if you prefer the old chart style, you can try this one

**Comment by smbt** [comment]
> @huangzhhui @asottile I deployed another version of star history using the previous chart lib
> https://old-star-history.t9t.io/
> if you prefer the old chart style, you can try this one

Awesome, thanks. I think even if it is "just star history" it is a worthwhile indicator, especially comparing different repos of the same type.
